version: '3'

services:
  publisher-backend:
    build: .
    restart: always
    ports:
      - 2222:2222
    networks:
      - scry_default
#    environment:
#      ENV=production
#   depends_on:
#     - "scry-server"
#    volumes:
#      - .:/home/python/publisher-backend

networks:
  scry_default:
    external: true
